language: php

php:
  - '5.5'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer run post-root-package-install
  - composer run post-create-project-cmd
  - composer run post-install-cmd

script: vendor/bin/phpunit